@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Mar 13 20:16:46 +0100 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto ae6277e3b48c4f16b5674f6da0f1abe6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot btn_in_tb_behav xil_defaultlib.btn_in_tb -log elaborate.log"
call xelab  -wto ae6277e3b48c4f16b5674f6da0f1abe6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot btn_in_tb_behav xil_defaultlib.btn_in_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
